// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqORQ1MQDQX4dMO3Yxh1RzXq9nX4lr4rY',
    appId: '1:645297868663:web:59cdfa69e528c3cb3f9b72',
    messagingSenderId: '645297868663',
    projectId: 'lumen-diary-jhg33',
    authDomain: 'lumen-diary-jhg33.firebaseapp.com',
    storageBucket: 'lumen-diary-jhg33.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS1uL1viTpc8phbqVOHfoKCDh9vmwW3CY',
    appId: '1:645297868663:android:21f9f65cbb23017f3f9b72',
    messagingSenderId: '645297868663',
    projectId: 'lumen-diary-jhg33',
    storageBucket: 'lumen-diary-jhg33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiJ7wi4ngsv6GKsiT6BKQxZtFqH4lAdLk',
    appId: '1:645297868663:ios:54fe59b0eaaae4843f9b72',
    messagingSenderId: '645297868663',
    projectId: 'lumen-diary-jhg33',
    storageBucket: 'lumen-diary-jhg33.firebasestorage.app',
    iosBundleId: 'com.example.lumen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiJ7wi4ngsv6GKsiT6BKQxZtFqH4lAdLk',
    appId: '1:645297868663:ios:54fe59b0eaaae4843f9b72',
    messagingSenderId: '645297868663',
    projectId: 'lumen-diary-jhg33',
    storageBucket: 'lumen-diary-jhg33.firebasestorage.app',
    iosBundleId: 'com.example.lumen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqORQ1MQDQX4dMO3Yxh1RzXq9nX4lr4rY',
    appId: '1:645297868663:web:ddc96e43d0c464b43f9b72',
    messagingSenderId: '645297868663',
    projectId: 'lumen-diary-jhg33',
    authDomain: 'lumen-diary-jhg33.firebaseapp.com',
    storageBucket: 'lumen-diary-jhg33.firebasestorage.app',
  );
}
